# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_compiler_0 || ORIG_REF_NAME==cic_compiler_0} -quiet] -quiet

# IP: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: D:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_compiler_0 || ORIG_REF_NAME==cic_compiler_0} -quiet] -quiet

# IP: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Xilinx/Vivado/project/final/final_002/final_002.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
